log = run_$(Cluster)_$(Process)_An_Emp_TimeReg_2019-07-31.log
error = run_$(Cluster)_$(Process)_An_Emp_TimeReg_2019-07-31.err
output = run_$(Cluster)_$(Process)_An_Emp_TimeReg_2019-07-31.out

executable = Run_An_Emp_TimeReg_2019-07-31.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = Data_An_Emp_TimeReg_2019-07-31.rda,Run_An_Emp_TimeReg_2019-07-31.R,Run_An_Emp_TimeReg_2019-07-31.sh
request_cpus = 24
queue 1
		