log = run_$(Cluster)_$(Process)_Aq_Emp_BrownMotion_2019-07-14.log
error = run_$(Cluster)_$(Process)_Aq_Emp_BrownMotion_2019-07-14.err
output = run_$(Cluster)_$(Process)_Aq_Emp_BrownMotion_2019-07-14.out

executable = Run_Aq_Emp_BrownMotion_2019-07-14.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = Data_Aq_Emp_BrownMotion_2019-07-14.rda,Run_Aq_Emp_BrownMotion_2019-07-14.R,Run_Aq_Emp_BrownMotion_2019-07-14.sh
request_cpus = 24
queue 1
		